### ISSUE TITLE
Puppet 4.9.0/4.9.1 breaks hiera-eyaml

### ISSUE THREAD

**Issue by svenmueller** [daenney/pupa#10]
After the latest puppet package was automatically installed, `hiera-eyaml` is not working anymore. Here is the matching bug report on puppet side for it: https://tickets.puppetlabs.com/browse/PUP-7209

**Comment by daenney** [comment]
Oh bugger. Thanks for raising the issue but I don't think there's anything to be done for now until upstream fixes it. I'll put up a notice in the README in the mean time.

**Comment by daenney** [comment]
Actually, your issue has been closed as a duplicate but the original ticket is still marked as resolved?

**Comment by daenney** [comment]
I've updated Pupa to Puppet 5, everything seems to work for me so I'm closing this.
